### PR TITLE
For Discussion - Table identification in queries

### PR DESCRIPTION
**Pull request by rathboma**
- only works in very basic cases
- needs deeper look-back (n token lookback)
- it is very confused by CTEs
- tests are a mess

### CODE REVIEW

**Comment by rathboma** [comment]
@MasterOdin what do you think to something like this? I think this feature would be an awesome addition to the library.

Something I think this needs:
- Some way to look-up CTES in the parser
- Some way to do an n token lookback in the parser

**Comment by MasterOdin** [comment]
I guess that my biggest thing would be that this is starting to increasingly pushing the library from just a simple query identifier to more of a query AST builder, and is that the direction want to take this library? A logical next step would be that we then also include the list of columns, and then after that maybe the where clause, etc.

Just want to make sure we're on the same page that that's what this library is looking like it might become, though maybe also is that the right direction for this library...

**Comment by rathboma** [comment]
I think we're increasingly needing something like that, and we'll want that to build a bunch of other shared features in the future - like quality autocomplete.

Not sure if it's better keeping this library focused and making something new that has a codebase custom built for purpose, or whether this library can be easily expanded.

**Comment by MasterOdin** [comment]
Yeah, makes sense. At some point will probably want to better rework the parsing algorithm since it kind of expects you to skip everything after identifying, and we're kind of bolting on new functionality, and I think there might be a cleaner way to accomplish what it does while have it extend better as we add in additional AST type features, but that's not pressing.

All in all, I'm fine with you continuing this thread of work, and I'm not against it, and that I don't think picking out the tables would make the library work any slower or anything for downstream users who don't need that feature.

**Comment by MasterOdin** [comment]
Closing in favor of #76

**Pull request closed without merging**
