### PR TITLE
Add initial support for table identification

### PR DESCRIPTION
**Pull request by azmy60**
This is a follow up PR for #69 (couldn't push commits to the original PR.)

Most of the stuff here is just updating the tests and limiting the table identification to simple queries using `SELECT`, `INSERT`, and non CTE. These are the stuff we'll need for now.

### CODE REVIEW

**Comment by rathboma** [comment]
@MasterOdin You good with this version of it?

**Review by MasterOdin — CHANGES_REQUESTED** [review]

**Comment by MasterOdin** [comment]
I think that combining using the same list of keywords for all statements isn't a super tenable approach to this problem. Even for selects, this'll fail for join statements, and that using the tokens (and how we've identified them, etc.) is the only way to approach this problem.

I would greatly prefer to hide this behind some sort of flag until it's more properly fleshed out so that beekeeper can enable and use it, but also not seeking bug reports on this feature that's barely implemented.

**Review by MasterOdin — APPROVED** [review]

**Comment by MasterOdin** [comment]
https://github.com/coresql/sql-query-identifier/releases/tag/v2.7.0

**Comment by azmy60** [comment]
Thank you!

**Pull request merged**
